name: Crear y subir imagen docker
on: 
  workflow_dispatch
  
jobs: 
  publish_imagen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar autenticación con Docker Hub
        run: echo "dckr_pat_aNrQH4kY7FnOXq6B_aclYtXlxLk" | docker login -u "johnarenales894" --password-stdin

      - name: Construir imagen Docker
        run: docker build -t johnarenales894/ejemplo-despliegue-express-actions:latest .

      - name: Subir imagen a Docker Hub
        run: docker push johnarenales894/ejemplo-despliegue-express-actions:latest