name: Crear y subir imagen docker
on: 
  workflow_dispatch
  
jobs: 
  publish_imagen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Construir imagen Docker
        run: docker build -t johnarenales894/ejemplo-despliegue-express-actions:${{ github.sha }} .

      - name: Subir imagen a Docker Hub
        run: docker push johnarenales894/ejemplo-despliegue-express-actions:${{ github.sha }}