name: Crear y subir imagen Docker

on:
  workflow_dispatch:

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login en Docker Hub
        run: echo "${{ secrets.ACTIONS_SECRET }}" | docker login -u "${{ secrets.USER_DOCKER }}" --password-stdin

      - name: Construir imagen
        run: docker build -t johnarenales894/despliegue-ejemplo:latest .

      - name: Subir imagen a Docker Hub
        run: docker push johnarenales894/despliegue-ejemplo:latest